sonar.projectKey=alexander-kirov_frontend-project-46
sonar.organization=alexander-kirov

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,__tests__/**,*.test.js,**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.verbose=true